<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603203801 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE channel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, allowed_media_type VARCHAR(10) NOT NULL, max_progression_allowed INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2F98E4761220EA6 ON channel (creator_id)');
        $this->addSql('CREATE TABLE channel_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, liked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, channel_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3037E3CDC86596CF ON channel_like (channel_id_id)');
        $this->addSql('CREATE INDEX IDX_3037E3CD9D86650F ON channel_like (user_id_id)');
        $this->addSql('CREATE TABLE channel_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, channel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_11C775377597D3FE ON channel_user (member_id)');
        $this->addSql('CREATE INDEX IDX_11C7753772F5A1AA ON channel_user (channel_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, media_url VARCHAR(255) DEFAULT NULL, media_type VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, channel_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9D86650F ON message (user_id_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FC86596CF ON message (channel_id_id)');
        $this->addSql('CREATE TABLE spoil_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_213B551780E261BC ON spoil_report (message_id_id)');
        $this->addSql('CREATE INDEX IDX_213B55179D86650F ON spoil_report (user_id_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(20) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, is_verified BOOLEAN NOT NULL, media_type VARCHAR(20) DEFAULT NULL, progression_anime INT DEFAULT NULL, progression_manga INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE channel ADD CONSTRAINT FK_A2F98E4761220EA6 FOREIGN KEY (creator_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE channel_like ADD CONSTRAINT FK_3037E3CDC86596CF FOREIGN KEY (channel_id_id) REFERENCES channel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE channel_like ADD CONSTRAINT FK_3037E3CD9D86650F FOREIGN KEY (user_id_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE channel_user ADD CONSTRAINT FK_11C775377597D3FE FOREIGN KEY (member_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE channel_user ADD CONSTRAINT FK_11C7753772F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9D86650F FOREIGN KEY (user_id_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FC86596CF FOREIGN KEY (channel_id_id) REFERENCES channel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE spoil_report ADD CONSTRAINT FK_213B551780E261BC FOREIGN KEY (message_id_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE spoil_report ADD CONSTRAINT FK_213B55179D86650F FOREIGN KEY (user_id_id) REFERENCES "users" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE channel DROP CONSTRAINT FK_A2F98E4761220EA6');
        $this->addSql('ALTER TABLE channel_like DROP CONSTRAINT FK_3037E3CDC86596CF');
        $this->addSql('ALTER TABLE channel_like DROP CONSTRAINT FK_3037E3CD9D86650F');
        $this->addSql('ALTER TABLE channel_user DROP CONSTRAINT FK_11C775377597D3FE');
        $this->addSql('ALTER TABLE channel_user DROP CONSTRAINT FK_11C7753772F5A1AA');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9D86650F');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FC86596CF');
        $this->addSql('ALTER TABLE spoil_report DROP CONSTRAINT FK_213B551780E261BC');
        $this->addSql('ALTER TABLE spoil_report DROP CONSTRAINT FK_213B55179D86650F');
        $this->addSql('DROP TABLE channel');
        $this->addSql('DROP TABLE channel_like');
        $this->addSql('DROP TABLE channel_user');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE spoil_report');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
